const questions = ["housed a friend from another school for Deltopia",
"-man?",
"-some?",
"caught yourself being too romantic with your fling",
"didn’t drink at the pregame but drank at the party",
"paid to get into a party",
"was rejected entrance at a frat party (as a girl)",
"submerged your whole body in the ocean",
"been kicked out of a party",
"had your bike stolen",
"stole a bike",
"caught someone with your stolen bike",
"crashed into someone on the bike path",
"spend over $1400 on rent",
"fucked without warning your roommates",
"had your picture taken by IV Streets",
"drank on the beach at night",
"stayed the night at non-bf/gf MPS’s apartment",
"non-bf/gf MPS stayed the night at your apartment",
"took a midterm while buzzed, crossed, or hungover",
"purchased a Plan B from IV Deli",
"got a temporary tattoo on DP",
"ate at Jesus Burger",
"actually swam in the FT pool",
"ate at the dining commons as an upperclassmen",
"was mentioned by someone else on the YikYak",
"hooked up with someone from your class",
"has at least one authentic review of yourself on GauchoGuys",
"participated in a protest on campus for more than 24 hours",
"hooked up with a ULA",
"isla vista. no shoes.",
"crushed on a TA or professor",
"tried to get more than two ribs from DLG",
"showered at an apartment that’s not yours",
"showered with more than one person",
"sex in the communal bathroom",
"has a pet in IV",
"ordered by police to pour out your drink",
"lost part of your security deposit for damage that wasn't you",
"went to a Halloween party",
"filmed a TikTok with a police officer",
"went viral on the UCSB Reddit or YikYak",
"asked or was asked your body count",
"got tested for an STD at student health",
"gave or received an STD or STI",
"watched the 'Deltopia' movie (horrible)",
"was at a party that got shut down by the police",
"DMed an ex or situationship after more than a month of no-contact",
"got tar on your feet from the beach",
"simultaneously conversed with two people you've seen naked",
"given or received a forehead kiss to a non-bf/gf MPS",
"was given an 'apartment tour' ;)",
"deleted Hinge",
"made an offensive comment about a racoon’s BMI",
"left your date at a party",
"streaked or been hazed in IV",
"went to Freebirds without shoes",
"ate in IV at midnight",
"ate someone out in the Davidson library",
"played volleyball or spikeball at the beach",
"was given sex-ED yet again by your ethnicity GE",
"joined an IV band",
"drunk texted or called your situationship",
"was given the personal phone number of a prof or TA",
"had Dank Bowls before it closed",
"skinny dipped in the ocean",
"is a part of a club and actually goes to all the meetings",
"had lunch or dinner with a professor who isn’t your research advisor",
" ",
"went on more than one balcony during Deltopia",
"was given free stuff at the Arbor or quad",
"was heckled at the quad by a student org",
"held a bag to someone’s face when they were about to yack",
"asked someone older than you for weed or alc",
"bought from the IV Farmacy",
"asked a question in class you already knew the answer to just to appear more intellectual",
"cuddled or made out with someone of the same gender (but you’re straight)",
"hooked up with your hometown ex during holiday",
"had your stomach pumped",
"had someone on your shoulders or been on someone’s shoulders at an IV band show",
"is a part of greek life that isn’t formally recognized by UCSB",
"camped on the bluffs",
"got written up by an RA",
"received free alc at a party",
"made out with someone you just met on DP",
"was interviewed on campus or DP",
"tried making a situationship official",
"got locked out",
"swang your keys around to feel the centripetal force on your fingers",
"got anything done at Precious Slut",
"got food poisoning at the dining commons",
"tried ketamine",
"became friends with someone while waiting in line for the bathroom at a party",
"was caught for using ChatGPT",
"drank alc that was poured into your mouth by someone else",
"submitted a regrade request for something you know is wrong",
"has mommy issues or attracts dudes with mommy issues",
"ghosted someone or has been ghosted ",
"overshared something to your fling",
"reviewed a boy on <a href='https://gauchoguys.com'>GauchoGuys.com</a>"

    ];
